- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: ajout adminitescia
      user: name=adminitescia
    - name: installation paquet
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
       - vim
       - htop
